# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{
  config,
  lib,
  pkgs,
  modulesPath,
  ...
}: {
  imports = [
    (modulesPath + "/installer/scan/not-detected.nix")
  ];

  boot.initrd.availableKernelModules = ["xhci_pci" "ahci" "usb_storage" "sd_mod" "sr_mod" "rtsx_usb_sdmmc"];
  boot.initrd.kernelModules = [];
  boot.kernelModules = ["kvm-intel"];
  boot.extraModulePackages = [];

  fileSystems."/" = {
    device = "/dev/disk/by-uuid/72a068cc-f1c7-40dd-8e0c-8e2ba12a3112";
    fsType = "ext4";
  };

  boot.initrd.luks.devices."luks-93b52e82-6b9c-4e97-ac48-d5f819fa8bb1".device = "/dev/disk/by-uuid/93b52e82-6b9c-4e97-ac48-d5f819fa8bb1";
  boot.initrd.luks.devices."luks-ac6946cd-ce24-4ca9-9801-e7327da5450a".device = "/dev/disk/by-uuid/ac6946cd-ce24-4ca9-9801-e7327da5450a";

  fileSystems."/boot" = {
    device = "/dev/disk/by-uuid/E345-6154";
    fsType = "vfat";
    options = ["fmask=0077" "dmask=0077"];
  };

  swapDevices = [
    {device = "/dev/disk/by-uuid/f18c636f-c792-496e-b862-923227d65d9d";}
  ];

  # Enables DHCP on each ethernet and wireless interface. In case of scripted networking
  # (the default) this is the recommended approach. When using systemd-networkd it's
  # still possible to use this option, but it's recommended to use it in conjunction
  # with explicit per-interface declarations with `networking.interfaces.<interface>.useDHCP`.
  networking.useDHCP = lib.mkDefault true;
  # networking.interfaces.enp1s0.useDHCP = lib.mkDefault true;
  # networking.interfaces.wlp2s0.useDHCP = lib.mkDefault true;

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
